server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka



